apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: provisioners.karpenter.sh
spec:
  group: karpenter.sh
  names:
    kind: Provisioner
    listKind: ProvisionerList
    plural: provisioners
    singular: provisioner
    categories:
      - karpenter
  scope: Cluster
  versions:
    - name: v1alpha5
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                consolidation:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                kubeletConfiguration:
                  type: object
                  properties:
                    clusterDNS:
                      type: array
                      items:
                        type: string
                    containerRuntime:
                      type: string
                    evictionHard:
                      type: object
                      additionalProperties:
                        type: string
                    kubeReserved:
                      type: object
                      additionalProperties:
                        type: integer
                    maxPods:
                      type: integer
                      minimum: 0
                    podsPerCore:
                      type: integer
                      minimum: 0
                    systemReserved:
                      type: object
                      additionalProperties:
                        type: integer
                labels:
                  type: object
                  additionalProperties:
                    type: string
                limits:
                  type: object
                  properties:
                    resources:
                      type: object
                      additionalProperties:
                        type: integer
                provider:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                providerRef:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                requirements:
                  type: array
                  items:
                    type: object
                    required:
                      - key
                      - operator
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      values:
                        type: array
                        items:
                          type: string
                startupTaints:
                  type: array
                  items:
                    type: object
                    required:
                      - effect
                      - key
                    properties:
                      effect:
                        type: string
                      key:
                        type: string
                      value:
                        type: string
                      timeAdded:
                        type: string
                taints:
                  type: array
                  items:
                    type: object
                    required:
                      - effect
                      - key
                    properties:
                      effect:
                        type: string
                      key:
                        type: string
                      value:
                        type: string
                      timeAdded:
                        type: string
                ttlSecondsAfterEmpty:
                  type: integer
                  format: int64
                ttlSecondsUntilExpired:
                  type: integer
                  format: int64
                weight:
                  type: integer
                  minimum: 1
                  maximum: 100
      subresources:
        status: {}
